"""Add style column to ArticleBlock

Revision ID: 65e76fbdcbb8
Revises: 0c9953efb090
Create Date: 2025-11-10 10:19:27.354165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '65e76fbdcbb8'
down_revision: Union[str, Sequence[str], None] = '0c9953efb090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_block', 'index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'article_block', type_='foreignkey')
    op.drop_constraint(None, 'article_block', type_='foreignkey')
    op.drop_column('article_block', 'next_id')
    op.drop_column('article_block', 'previous_id')
    op.drop_column('articles', 'tags_css')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('tags_css', sqlite.JSON(), nullable=True))
    op.add_column('article_block', sa.Column('previous_id', sa.INTEGER(), nullable=True))
    op.add_column('article_block', sa.Column('next_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'article_block', 'article_block', ['next_id'], ['id'])
    op.create_foreign_key(None, 'article_block', 'article_block', ['previous_id'], ['id'])
    op.alter_column('article_block', 'index',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
