"""fix title column2

Revision ID: a6b22c32ff9d
Revises: bb77c7523215
Create Date: 2025-09-04 16:11:04.476277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b22c32ff9d'
down_revision: Union[str, Sequence[str], None] = 'bb77c7523215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testmodel', sa.Column('c', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testmodel', 'c')
    # ### end Alembic commands ###
