"""fix title column

Revision ID: bb77c7523215
Revises: 4d93c9d956ea
Create Date: 2025-09-04 16:07:37.612997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb77c7523215'
down_revision: Union[str, Sequence[str], None] = '4d93c9d956ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testmodel', sa.Column('a', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testmodel', 'a')
    # ### end Alembic commands ###
