"""20250924 add ArticleBlock model

Revision ID: bc84143568b5
Revises: a6b22c32ff9d
Create Date: 2025-09-24 16:40:44.261670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc84143568b5'
down_revision: Union[str, Sequence[str], None] = 'a6b22c32ff9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_type', sa.String(), nullable=True),
    sa.Column('marked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['next_id'], ['article_block.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['article_block.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_block_id'), 'article_block', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_block_id'), table_name='article_block')
    op.drop_table('article_block')
    # ### end Alembic commands ###
