"""ArticleBlock model add index column

Revision ID: 2bb782999f4c
Revises: bc84143568b5
Create Date: 2025-10-13 11:26:28.443024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2bb782999f4c'
down_revision: Union[str, Sequence[str], None] = 'bc84143568b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('article_block', sa.Column('index', sa.Integer(), nullable=False))
#     op.add_column('article_block', sa.Column('previous_index', sa.Integer(), nullable=True))
#     op.add_column('article_block', sa.Column('next_index', sa.Integer(), nullable=True))
#     op.create_index('ix_article_block_article', 'article_block', ['article_id'], unique=False)
#     op.drop_constraint(None, 'article_block', type_='foreignkey')
#     op.drop_constraint(None, 'article_block', type_='foreignkey')
#     op.drop_column('article_block', 'next_id')
#     op.drop_column('article_block', 'previous_id')
#     op.drop_column('articles', 'tags_css')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('articles', sa.Column('tags_css', sqlite.JSON(), nullable=True))
#     op.add_column('article_block', sa.Column('previous_id', sa.INTEGER(), nullable=True))
#     op.add_column('article_block', sa.Column('next_id', sa.INTEGER(), nullable=True))
#     op.create_foreign_key(None, 'article_block', 'article_block', ['next_id'], ['id'])
#     op.create_foreign_key(None, 'article_block', 'article_block', ['previous_id'], ['id'])
#     op.drop_index('ix_article_block_article', table_name='article_block')
#     op.drop_column('article_block', 'next_index')
#     op.drop_column('article_block', 'previous_index')
#     op.drop_column('article_block', 'index')
#     # ### end Alembic commands ###
# from alembic import op
# import sqlalchemy as sa



# def upgrade():
#     with op.batch_alter_table('article_block', schema=None) as batch_op:
#         batch_op.add_column(
#             sa.Column('index', sa.Integer(), nullable=False, server_default="0")
#         )


# def downgrade():
#     with op.batch_alter_table('article_block', schema=None) as batch_op:
#         batch_op.drop_column('index')